-- migrations/0041_session_config_dir.sql
-- Per-session Claude config dir: which Claude login a session boots on.
--
-- A session can be pointed at a second account by exporting CLAUDE_CONFIG_DIR
-- in its launch line. The chosen directory is stored here so the launch
-- builder, the Resume picker and recall all read one value.
--
-- The empty string is the "daemon default" sentinel (the server process's own
-- $CLAUDE_CONFIG_DIR, else ~/.claude), so every existing row keeps exactly
-- today's behaviour and no call site changes meaning.
--
-- NOT NULL + DEFAULT '' keeps `sessions::create`'s explicit column list, the
-- test-only `insert_minimal` and `duplicate`'s SELECT-INSERT valid without
-- touching a single existing statement. No CHECK constraint: the path rules
-- (absolute, existing directory, charset) are validated in `sessions::create`,
-- which can answer 400 with the reason. A CHECK here would turn a future rule
-- change into a schema migration.
ALTER TABLE sessions ADD COLUMN config_dir TEXT NOT NULL DEFAULT '';
